#!/bin/bash

source $( project --prefix )/lib/helpers

LIST=$(git status --porcelain | grep -E '^[^D\?][^D\?].*\.php$' | awk '{print $2}')
ERRORS=false

writeln "<comment>PHP Lint - pre-commit hook syntax checker</comment>"

for file in $LIST
do
    ERROR=$(php -l $file 2>&1 | grep "^Parse error")

    if [ "$ERROR" != "" ]; then
        writeln "<error>Syntax errors found in file:</error> $file"
        writeln "$ERROR"
        ERRORS=true
    fi
done
if [ $ERRORS = true ]; then
    writeln "<error>Can't commit, fix errors first</error>"
    exit 1
else
    if (( "${#LIST[@]}" > 1 )); then
        writeln "<info>No errors were found.</info>"
    fi
    exit 0
fi